apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "hrmitra.fullname" . }}-web
spec:
  replicas: {{ .Values.rails.replicas }}
  selector:
    matchLabels:
      app: {{ include "hrmitra.fullname" . }}-web
  template:
    metadata:
      labels:
        app: {{ include "hrmitra.fullname" . }}-web
    spec:
      containers:
        - name: rails
          image: "{{ .Values.rails.image.repository }}:{{ .Values.rails.image.tag }}"
          imagePullPolicy: {{ .Values.rails.image.pullPolicy }}
          ports:
            - containerPort: 3000
          env:
            - name: RAILS_ENV
              value: {{ .Values.rails.env.RAILS_ENV }}
            - name: RAILS_MASTER_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ include "hrmitra.fullname" . }}-secrets
                  key: RAILS_MASTER_KEY
            - name: DATABASE_HOST
              value: {{ include "hrmitra.fullname" . }}-db
            - name: DATABASE_USER
              value: {{ .Values.postgres.user }}
            - name: DATABASE_PASSWORD
              value: {{ .Values.postgres.password }}
            - name: DATABASE_NAME
              value: {{ .Values.postgres.db }}
          command: ["./bin/rails", "server", "-b", "0.0.0.0", "-p", "3000"]
          resources:
            {{- toYaml .Values.rails.resources | nindent 12 }}
          readinessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 5
