version: "3.9"

services:
  web:
    build: .
    container_name: hr_mitra_web
    command: ./bin/rails server -b 0.0.0.0 -p 3000
    ports:
      - "3000:3000"
    environment:
      RAILS_ENV: development
      RAILS_MASTER_KEY: 2a4b8c0e7430174f78cd957189cef2ab
      DATABASE_HOST: db
      DATABASE_USER: developer
      DATABASE_PASSWORD: developer
      DATABASE_NAME: hr_mitra_development
    volumes:
      - ".:/rails"
    depends_on:
      - db
    networks:
      - app_network

  db:
    image: postgres:15
    container_name: hr_mitra_db
    environment:
      POSTGRES_USER: developer
      POSTGRES_PASSWORD: developer
      POSTGRES_DB: hr_mitra_development
    volumes:
      - "postgres_data:/var/lib/postgresql/data"
    networks:
      - app_network

volumes:
  postgres_data:

networks:
  app_network:
    driver: bridge
